### ISSUE TITLE
Other requirements

### ISSUE THREAD

**Issue by jkazuop** [staranjeet/dictionary-cli#1]
Cool tool! Ran into some requirements issues, though. After running `pip install greb`, I also needed to install the following:
- lxml
- html5lib
- ndg-httpsclient
- pyasn1

Should these be added to your requirements.txt?

**Comment by taranjeet** [comment]
No. I just checked it in a new virtual env. It only requires requests, coloroma, bs4, and docopt. What python version and os are you using?

**Comment by jkazuop** [comment]
Ah, ok. I'm using Python 2.7.10 on OS X Yosemite 10.10.5.
