### ISSUE TITLE
Some words return no meaning

### ISSUE THREAD

**Issue by jkazuop** [staranjeet/dictionary-cli#2]
I was testing out this program and found that some words don't return any meaning. It turns out that some pages on merriam-webster.com place the definition of the word inside 
of `<div class='ld_on_collegiate'>` tags, where other pages store the definition inside of `<span class='ssens'>` tags. I haven't run into any other places that the definition is stored, but just thought I'd let you know about this issue! 

Some example words that return no meaning: pie and ass. Don't ask me why I was searching those lol.

**Comment by taranjeet** [comment]
@jkazuop : Thanks. I will look into this and fix it out soon.

**Comment by taranjeet** [comment]
I have fixed the issue. You can upgrade the package by running
`pip install --upgrade greb`

**Comment by jkazuop** [comment]
Issue is resolved as of 0.0.3 release.

**Comment by taranjeet** [comment]
@jkazuop : version 0.0.4 also lists suggestion in case the word is not spelled correctly. Try upgrading it once and let me know if it breaks in any case.

**Comment by jkazuop** [comment]
@staranjeet : I like the new feature! Sure, I'll let you know.
